version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  notification_service:
    build: .
    container_name: notification_service
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NO_AUTHORIZATION=${NO_AUTHORIZATION}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "8000:8000"
  test:
    build:
      context: .
    command: python -m pytest tests/test_main.py && python -m pytest tests/test_e2e.py
    volumes:
      - .:/app
    depends_on:
      - redis
      - notification_service
